"""
Word 測試報告生成模組

生成包含圖文內容的專業測試報告
- 封面頁
- 測試摘要
- 測試結果表格
- 圖表 (通過率圓餅圖、各類型長條圖)
- 截圖 (可選)
"""

import tempfile
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional

try:
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    HAS_DOCX = True
except ImportError:
    HAS_DOCX = False

from rich.console import Console

from .reporters import (
    HAS_MATPLOTLIB,
    create_pass_rate_chart,
    create_test_type_chart,
    set_cell_shading,
    format_duration,
    format_table_duration,
    rgb,
    build_single_test_case,
    TYPE_LABELS,
    TYPE_DESCRIPTIONS,
    COLOR_PASS_RGB,
    COLOR_FAIL_RGB,
    COLOR_GREY_RGB,
    COLOR_LIGHT_GREY_RGB,
    COLOR_SUBTITLE_RGB,
    COLOR_HEADER_HEX,
    COLOR_LABEL_BG_HEX,
    COLOR_PASS_BG_HEX,
    COLOR_FAIL_BG_HEX,
)

console = Console()


def generate_word_report(
    project_name: str,
    test_results: Dict,
    output_path: str,
    screenshots: List[str] = None,
    include_charts: bool = True
) -> str:
    """
    生成 Word 測試報告

    Args:
        project_name: 專案名稱
        test_results: 測試結果字典 (來自 test_suite)
        output_path: 輸出檔案路徑
        screenshots: 截圖路徑列表 (可選)
        include_charts: 是否包含圖表

    Returns:
        輸出檔案路徑
    """
    if not HAS_DOCX:
        raise ImportError("請安裝 python-docx: pip install python-docx")

    doc = Document()

    # 設定文件樣式
    style = doc.styles['Normal']
    style.font.name = 'Microsoft JhengHei'
    style.font.size = Pt(12)

    # ========== 封面頁 ==========
    _build_cover_page(doc, project_name, test_results)
    doc.add_page_break()

    # ========== 測試摘要 ==========
    summary = test_results.get('summary', {})
    total_passed = summary.get('total_passed', 0)
    total_failed = summary.get('total_failed', 0)
    total_duration = summary.get('total_duration', 0)
    coverage = summary.get('coverage', 0)

    # 如果 total_duration 為 0，從各測試類型的 test_cases 計算
    if total_duration == 0:
        tests = test_results.get('tests', {})
        for result in tests.values():
            test_cases = result.get('test_cases', [])
            total_duration += sum(tc.get('duration', 0) for tc in test_cases)

    _build_summary_section(doc, total_passed, total_failed, total_duration, coverage)

    # ========== 通過率圖表 ==========
    if include_charts and HAS_MATPLOTLIB:
        _insert_chart(doc, '測試通過率',
                      create_pass_rate_chart(total_passed, total_failed),
                      width=Inches(3.5))

    # ========== 各類型測試結果 ==========
    tests = test_results.get('tests', {})
    configured_tests = {k: v for k, v in tests.items() if not v.get('not_configured', False)}
    _build_test_results_table(doc, configured_tests)

    # ========== 詳細測試案例列表 (含截圖) ==========
    _build_test_case_details(doc, configured_tests)

    # ========== 各類型長條圖 ==========
    if include_charts and HAS_MATPLOTLIB and tests:
        _insert_chart(doc, '測試結果分布',
                      create_test_type_chart(tests),
                      width=Inches(6), heading_level=2)

    doc.add_page_break()

    # ========== 測試類型說明 ==========
    _build_type_descriptions(doc)

    # ========== 額外截圖 (可選) ==========
    if screenshots:
        _build_extra_screenshots(doc, screenshots)

    # ========== 頁尾 ==========
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer_run = footer.add_run('Generated by DashAI DevTools')
    footer_run.font.size = Pt(10)
    footer_run.font.color.rgb = rgb(COLOR_LIGHT_GREY_RGB)

    # 儲存文件
    output_file = Path(output_path)
    doc.save(output_file)

    return str(output_file)


def _build_cover_page(doc, project_name: str, test_results: Dict):
    """建立封面頁"""
    # 標題
    title = doc.add_heading('', level=0)
    title_run = title.add_run(f'{project_name} 測試報告')
    title_run.font.size = Pt(36)
    title_run.font.bold = True
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # 副標題
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    sub_run = subtitle.add_run('四大類型測試套件執行結果')
    sub_run.font.size = Pt(18)
    sub_run.font.color.rgb = rgb(COLOR_SUBTITLE_RGB)

    # 日期
    doc.add_paragraph()
    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    timestamp = test_results.get('timestamp', datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    date_run = date_para.add_run(f'報告產生時間: {timestamp}')
    date_run.font.size = Pt(14)

    # 狀態標示
    doc.add_paragraph()
    doc.add_paragraph()
    status_para = doc.add_paragraph()
    status_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    overall_success = test_results.get('overall_success', True)
    if overall_success:
        status_run = status_para.add_run('ALL TESTS PASSED')
        status_run.font.color.rgb = rgb(COLOR_PASS_RGB)
    else:
        status_run = status_para.add_run('SOME TESTS FAILED')
        status_run.font.color.rgb = rgb(COLOR_FAIL_RGB)

    status_run.font.size = Pt(24)
    status_run.font.bold = True


def _build_summary_section(doc, total_passed: int, total_failed: int,
                           total_duration: float, coverage: float):
    """建立測試摘要區段"""
    doc.add_heading('測試摘要', level=1)

    summary_table = doc.add_table(rows=5, cols=2)
    summary_table.style = 'Table Grid'

    duration_str = format_duration(total_duration)

    summary_data = [
        ('總測試數', str(total_passed + total_failed)),
        ('通過', str(total_passed)),
        ('失敗', str(total_failed)),
        ('執行時間', duration_str),
        ('程式碼覆蓋率', f'{coverage:.1f}%' if coverage > 0 else 'N/A'),
    ]

    for i, (label, value) in enumerate(summary_data):
        row = summary_table.rows[i]
        row.cells[0].text = label
        row.cells[1].text = value
        set_cell_shading(row.cells[0], COLOR_LABEL_BG_HEX)

    doc.add_paragraph()


def _insert_chart(doc, title: str, chart_data: Optional[bytes],
                  width=None, heading_level: int = 2):
    """插入圖表到文件"""
    doc.add_heading(title, level=heading_level)

    if chart_data:
        with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as tmp:
            tmp.write(chart_data)
            tmp_path = tmp.name

        doc.add_picture(tmp_path, width=width)
        last_paragraph = doc.paragraphs[-1]
        last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER

        Path(tmp_path).unlink(missing_ok=True)

    doc.add_paragraph()


def _build_test_results_table(doc, configured_tests: Dict):
    """建立各類型測試結果表格"""
    doc.add_heading('各類型測試結果', level=1)

    if not configured_tests:
        p = doc.add_paragraph()
        run = p.add_run('此專案未設定任何測試框架')
        run.font.color.rgb = rgb(COLOR_GREY_RGB)
        run.italic = True
        doc.add_paragraph()
        return

    result_table = doc.add_table(rows=len(configured_tests) + 1, cols=5)
    result_table.style = 'Table Grid'

    # 表頭
    header_row = result_table.rows[0]
    headers = ['測試類型', '狀態', '通過', '失敗', '時間']
    for i, header in enumerate(headers):
        cell = header_row.cells[i]
        cell.text = header
        set_cell_shading(cell, COLOR_HEADER_HEX)
        for paragraph in cell.paragraphs:
            for run in paragraph.runs:
                run.font.bold = True
                run.font.color.rgb = RGBColor(255, 255, 255)

    # 資料列
    for i, (test_type, result) in enumerate(configured_tests.items(), start=1):
        row = result_table.rows[i]
        row.cells[0].text = TYPE_LABELS.get(test_type, test_type)

        success = result.get('success', True)
        row.cells[1].text = 'PASS' if success else 'FAIL'
        status_cell = row.cells[1]
        if success:
            set_cell_shading(status_cell, COLOR_PASS_BG_HEX)
        else:
            set_cell_shading(status_cell, COLOR_FAIL_BG_HEX)

        row.cells[2].text = str(result.get('passed', 0))
        row.cells[3].text = str(result.get('failed', 0))

        # 計算總時間
        duration = result.get('duration', 0)
        if duration == 0:
            test_cases = result.get('test_cases', [])
            duration = sum(tc.get('duration', 0) for tc in test_cases)
        row.cells[4].text = format_table_duration(duration)

    doc.add_paragraph()


def _build_test_case_details(doc, configured_tests: Dict):
    """建立詳細測試案例列表 (含截圖)"""
    for test_type, result in configured_tests.items():
        test_cases = result.get('test_cases', [])
        if not test_cases:
            continue

        doc.add_page_break()
        doc.add_heading(f'{TYPE_LABELS.get(test_type, test_type)} - 測試案例明細', level=1)

        for i, tc in enumerate(test_cases, start=1):
            build_single_test_case(doc, tc, i)


def _build_type_descriptions(doc):
    """建立測試類型說明區段"""
    doc.add_heading('測試類型說明', level=1)

    for title, desc in TYPE_DESCRIPTIONS:
        p = doc.add_paragraph()
        title_run = p.add_run(title + ': ')
        title_run.bold = True
        p.add_run(desc)
        doc.add_paragraph()


def _build_extra_screenshots(doc, screenshots: List[str]):
    """建立補充截圖區段"""
    doc.add_page_break()
    doc.add_heading('補充截圖', level=1)

    for i, screenshot_path in enumerate(screenshots):
        if Path(screenshot_path).exists():
            p = doc.add_paragraph()
            run = p.add_run(f'截圖 {i + 1}')
            run.bold = True
            run.font.size = Pt(12)

            doc.add_picture(screenshot_path, width=Inches(6))
            last_paragraph = doc.paragraphs[-1]
            last_paragraph.alignment = WD_ALIGN_PARAGRAPH.CENTER
            doc.add_paragraph()


def take_screenshots(project_path: str, urls: List[str] = None) -> List[str]:
    """
    使用 Puppeteer 截取頁面截圖

    Args:
        project_path: 專案路徑
        urls: 要截圖的 URL 列表

    Returns:
        截圖檔案路徑列表
    """
    import subprocess
    import tempfile

    if not urls:
        # 預設截圖頁面
        urls = [
            'https://demo-app.vercel.app/',
            'https://demo-app.vercel.app/warehouse/transfer',
            'https://demo-app.vercel.app/warehouse/line-side',
        ]

    screenshots = []
    screenshot_dir = Path(tempfile.mkdtemp(prefix='test-screenshots-'))

    # Puppeteer 截圖腳本
    for i, url in enumerate(urls):
        screenshot_path = screenshot_dir / f'screenshot-{i+1}.png'
        script = f'''
const puppeteer = require("puppeteer");
(async () => {{
  const browser = await puppeteer.launch({{ headless: "new" }});
  const page = await browser.newPage();
  await page.setViewport({{ width: 1920, height: 1080 }});
  await page.goto("{url}", {{ waitUntil: "networkidle0", timeout: 30000 }});
  await new Promise(r => setTimeout(r, 2000));
  await page.screenshot({{ path: "{screenshot_path}", fullPage: false }});
  await browser.close();
}})();
'''
        try:
            puppeteer_dirs = [
                project_path
            ]

            for pdir in puppeteer_dirs:
                if (Path(pdir) / 'node_modules' / 'puppeteer').exists():
                    result = subprocess.run(
                        ['node', '-e', script],
                        cwd=pdir,
                        capture_output=True,
                        timeout=60
                    )
                    if result.returncode == 0 and screenshot_path.exists():
                        screenshots.append(str(screenshot_path))
                        console.print(f"[dim]  截圖: {url}[/dim]")
                    break
        except Exception as e:
            console.print(f"[yellow]截圖失敗: {url} - {e}[/yellow]")

    return screenshots


def run_and_generate_report(
    project_path: str,
    output_path: str = None,
    test_types: List[str] = None,
    include_screenshots: bool = True,
    screenshot_urls: List[str] = None
) -> Dict:
    """
    執行測試並生成 Word 報告

    Args:
        project_path: 專案路徑
        output_path: 輸出路徑 (預設為專案目錄下的 test-report.docx)
        test_types: 測試類型列表
        include_screenshots: 是否包含截圖 (預設 True)
        screenshot_urls: 要截圖的 URL 列表

    Returns:
        結果字典
    """
    from .test_suite import TestSuiteRunner

    project = Path(project_path).resolve()
    project_name = project.name

    if not output_path:
        output_path = str(project / f'{project_name}-test-report.docx')

    # 執行測試
    console.print(f"[cyan]執行 {project_name} 測試套件...[/cyan]")
    runner = TestSuiteRunner(project_path)
    suite_result = runner.run_all(test_types)

    # 準備測試結果 (包含測試案例明細)
    test_results = {
        'project': project_name,
        'timestamp': suite_result.timestamp,
        'overall_success': suite_result.overall_success,
        'summary': {
            'total_passed': suite_result.total_passed,
            'total_failed': suite_result.total_failed,
            'total_duration': suite_result.total_duration,
            'coverage': suite_result.coverage
        },
        'tests': {
            k: {
                'success': v.success,
                'passed': v.passed,
                'failed': v.failed,
                'duration': v.duration,
                'coverage': v.coverage,
                'not_configured': v.not_configured,
                'test_cases': [
                    {
                        'name': tc.name,
                        'status': tc.status,
                        'duration': tc.duration,
                        'error': tc.error,
                        'screenshot': tc.screenshot,
                        'api_response': tc.api_response,
                        'terminal_output': tc.terminal_output
                    }
                    for tc in v.test_cases
                ]
            }
            for k, v in suite_result.results.items()
        }
    }

    # 額外截圖
    screenshots = []
    if include_screenshots and screenshot_urls:
        console.print(f"[cyan]擷取補充截圖...[/cyan]")
        screenshots = take_screenshots(project_path, screenshot_urls)

    # 生成報告
    console.print(f"[cyan]生成 Word 報告...[/cyan]")
    report_path = generate_word_report(
        project_name=project_name,
        test_results=test_results,
        output_path=output_path,
        screenshots=screenshots,
        include_charts=True
    )

    console.print(f"[green]報告已生成: {report_path}[/green]")

    return {
        'success': True,
        'report_path': report_path,
        'test_results': test_results
    }
